### ISSUE TITLE
Error: Cannot find module 'babel-runtime/helpers/toConsumableArray' from '.../node_modules/redux-saga-tester/dist'

### ISSUE THREAD

**Issue by bstro** [wix/redux-saga-tester#3]
Attempting to use `redux-saga-tester` in my app and running into this error... (sorry about the terrible formatting, not sure how to make it better...)

`The Broccoli Plugin: [object Object] failed with:
Error: Cannot find module 'babel-runtime/helpers/toConsumableArray' from '.../node_modules/redux-saga-tester/dist'
    at .../node_modules/ember-browserify/node_modules/browserify/node_modules/resolve/lib/async.js:46:17
    at process (.../node_modules/ember-browserify/node_modules/browserify/node_modules/resolve/lib/async.js:173:43)
    at ondir (.../node_modules/ember-browserify/node_modules/browserify/node_modules/resolve/lib/async.js:188:17)
    at load (.../node_modules/ember-browserify/node_modules/browserify/node_modules/resolve/lib/async.js:69:43)
    at onex (.../node_modules/ember-browserify/node_modules/browserify/node_modules/resolve/lib/async.js:92:31)
    at .../node_modules/ember-browserify/node_modules/browserify/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:82:15)`

Any ideas?

**Comment by 3LOK** [comment]
Hi @bstro - was this issue ever solved? I see no one else encountered it.

**Comment by 3LOK** [comment]
Closing due to inactivity.
