### ISSUE TITLE
.done undefined (Cannot read property 'then' of undefined) with take(eventChannel)

### ISSUE THREAD

**Issue by drmikecrowe** [wix/redux-saga-tester#56]
Using an `eventChannel` in a saga as such:

```
export function connectFsm(fdf) {
    return eventChannel(emit => {
        const onBeforeTransition = state => {
            return new Promise((resolve, reject) => {
                emit({ event: state.event, type: state.type, resolve: resolve, reject: reject });
            });
        };
        return () => {
            fdf.onBeforeTransition = null;
        };
    });
}

export function* stateMachineDriver() {
    yield put(fsmCreate());
    const myClient = connectFsm(fsmDispatchFunctions);
    while (true) {
        let action = yield take(myClient);
        if (action.event === "onEnterState" || action.event === "onTransition") {
            action.resolve();
            yield fork(fsmDispatch, action);
        }
    }
}
```

In my test, I'm initializing it as follows:

```
    it("can create the state-machine", async function() {
        sagaTester = new SagaTester({
            initialState: state,
            reducers: fsmStateReducer,
            middlewares : [middleware],
            options,
        });
        sagaTester.start(stateMachineDriver);
        await sagaTester.waitFor(FSM_CREATE);
        state = sagaTester.getState();
    });
```

My code causing this is this line:

```
        let action = yield take(myClient);
```

in your code here:
```
    start(sagas = [], ...args) {
        const task = this.sagaMiddleware.run(sagas, ...args);
        task.done.then(() => this._verifyAwaitedActionsCalled());
```

The error is:

```
  ● State Machine Sequence Test › can create the state-machine

    TypeError: Cannot read property 'then' of undefined

      24 |             options,
      25 |         });
    > 26 |         sagaTester.start(stateMachineDriver);
         |                    ^
      27 | 
      28 |         await sagaTester.waitFor(FSM_CREATE);
      29 |         state = sagaTester.getState();

      at SagaIntegrationTester.start (node_modules/redux-saga-tester/dist/SagaTester.js:182:23)
      at Object.<anonymous> (src/store/app/fsm/states/test/StateTester.test.ts:26:20)
      at src/store/app/fsm/states/test/StateTester.test.ts:7:71
      at Object.<anonymous>.__awaiter (src/store/app/fsm/states/test/StateTester.test.ts:3:12)
      at Object.<anonymous> (src/store/app/fsm/states/test/StateTester.test.ts:22:16)
```

If I wrap `sagaTester.start(stateMachineDriver);` in a try/catch and ignore this error, the test completes successfully (so `await sagaTester.waitFor(FSM_CREATE);` succeeds.

If I trap on that error, the object returned from the `let action = yield take(myClient);` line is:

![pasted_image](https://user-images.githubusercontent.com/90312/51712613-597c0e00-1ffd-11e9-9a7a-331549e5fc07.png)

**Comment by drmikecrowe** [comment]
Actually, this isn't solved yet, sorry.  I closed this issue by mistake.

My solution:

```
    start(sagas = [], ...args) {
        const task = this.sagaMiddleware.run(sagas, ...args);
        if (!task.done && task.toPromise) task.done = task.toPromise();     // <<--- add this 
        task.done.then(() => this._verifyAwaitedActionsCalled());
        task.done.catch(e => this._handleRootSagaException(e));
        return task;
    }
```

**Comment by unixc3t** [comment]
I also have this problem.

**Comment by bramski** [comment]
I also have this issue and need it reopened. I've duplicated it so I can submit a PR.

**Comment by bramski** [comment]
Yeah this is basically because it's not properly supporting redux-saga 1.0.0: See: https://github.com/wix/redux-saga-tester/issues/57
