### ISSUE TITLE
Babel dependency issue

### ISSUE THREAD

**Issue by danni** [wix/redux-saga-tester#61]
Getting this issue when installing with `yarn`:

```
Cannot find module 'babel-runtime/core-js/promise'
Error: Cannot find module 'babel-runtime/core-js/promise'
    at Module._resolveFilename (internal/modules/cjs/loader.js:584:15)
    at Function.Module._resolveFilename (/Users/danni/src/SPT/spt-bridge/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/common/reset-search-paths.js:43:12)
    at Function.Module._load (internal/modules/cjs/loader.js:510:25)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/danni/src/SPT/spt-bridge/node_modules/redux-saga-tester/dist/SagaTester.js:8:16)
    at Object.<anonymous> (/Users/danni/src/SPT/spt-bridge/node_modules/redux-saga-tester/dist/SagaTester.js:326:3
```

I'm using Babel 7. Adding `babel-runtime` 6 does seem to solve the issue.

**Comment by InterAl** [comment]
@danni - can't reproduce. Try installing in a new, clean directory, as it might be something with your project configuration.

**Comment by danni** [comment]
Hi, I'm installing into a pretty new project that just contains the Babel 7 bootstrap, React, Redux, Saga, etc. Did you install with `yarn` or `npm`? I'm guessing the problem is that dev dependencies of the dev dependencies aren't getting installed.

**Comment by InterAl** [comment]
I installed with yarn: yarn add redux-saga-tester. Everything worked fine.

**Comment by danni** [comment]
I did `yarn add --dev redux-saga-tester`. I'm pretty sure it has nothing to do with my project configuration, and is to do with the dependency not being pulled in. Manually installing `babel-runtime` 6 resolves it.

**Comment by InterAl** [comment]
@danni - added babel-runtime as a dependency. Should resolve this issue.

**Comment by danni** [comment]
Confirmed!
